spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/sistema?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: joice
    password: password